# Generated by Django 3.0.7 on 2020-07-04 07:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200704_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_img.png', upload_to=''),
        ),
    ]
